version: 0.1
            
phases:

  install: 
    commands:
      - go get -u https://github.com/golang/lint/blob/6edffad5e616/golint/ #github.com/golang/lint/golint/golint.go

  pre_build: 
    commands:

      # Ensure code passes all lint tests
      - golint -set_exit_status

      # Run all tests included with our application
      - go test

  build:
    commands:

      # Build our application
      - go build -o app

artifacts:
  files:
    - app
    #- appspec.yml
    - buildspec.yml
    - config/*
    # - codedeploy/*
    - cloudformation/*
